2024-08-08 16:09:49.268|background-preinit|INFO |o.h.v.internal.util.Version.?:?|IGNORE|||||||||||||||||||||||||||||HV000001: Hibernate Validator 6.2.5.Final
2024-08-08 16:09:49.293|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Starting Application using Java 1.8.0_421 on DESKTOP-0D3FQF2 with PID 18644 (C:\Users\25538\source\java\share-liteflow\share-liteflow-web\target\classes started by 25538 in C:\Users\25538\source\java\share-liteflow)
2024-08-08 16:09:49.294|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||The following 1 profile is active: "local"
2024-08-08 16:09:49.363|main|WARN |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] config[dataId=file-server-local.yml, group=yun-demo-service] is empty
2024-08-08 16:09:49.363|main|WARN |c.a.c.n.c.NacosConfigDataLoader.logTo:258|IGNORE|||||||||||||||||||||||||||||[Nacos Config] config[dataId=user-server-local.yml, group=yun-demo-service] is empty
2024-08-08 16:09:49.364|main|WARN |c.a.c.n.c.NacosConfigDataLoader.logTo:258|IGNORE|||||||||||||||||||||||||||||[Nacos Config] config[dataId=redis-local.yml, group=yun-demo-service] is empty
2024-08-08 16:09:49.365|main|WARN |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] config[dataId=feign-local.yml, group=yun-demo-service] is empty
2024-08-08 16:09:49.366|main|WARN |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] config[dataId=mysql-local.yml, group=yun-demo-service] is empty
2024-08-08 16:09:50.273|main|ERROR|o.s.boot.SpringApplication.?:?|IGNORE|||||||||||||||||||||||||||||Application run failed
j.lang.IllegalStateException: Service id not legal hostname (${file-server})
	at o.springframework.util.Assert.state(Assert.java:76)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:111)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:282)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:270)
	at o.s.c.o.FeignClientsRegistrar.getContextId(FeignClientsRegistrar.java:288)
	at o.s.c.o.FeignClientsRegistrar.registerFeignClient(FeignClientsRegistrar.java:213)
	at o.s.c.o.FeignClientsRegistrar.registerFeignClients(FeignClientsRegistrar.java:202)
	at o.s.c.o.FeignClientsRegistrar.registerBeanDefinitions(FeignClientsRegistrar.java:151)
	at o.s.c.a.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86)
	at o.s.c.a.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396)
	... 15 frames truncated
2024-08-08 16:09:50.277|Thread-9|WARN |c.a.n.c.notify.NotifyCenter.?:?|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Start destroying Publisher
2024-08-08 16:09:50.277|Thread-5|WARN |c.a.n.c.h.HttpClientBeanHolder.shutdown:108|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Start destroying common HttpClient
2024-08-08 16:09:50.277|Thread-9|WARN |c.a.n.c.notify.NotifyCenter.shutdown:153|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Destruction of the end
2024-08-08 16:09:50.278|Thread-5|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Destruction of the end
2024-08-08 16:22:18.722|background-preinit|INFO |o.h.v.internal.util.Version.?:?|IGNORE|||||||||||||||||||||||||||||HV000001: Hibernate Validator 6.2.5.Final
2024-08-08 16:22:18.753|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Starting Application using Java 1.8.0_421 on DESKTOP-0D3FQF2 with PID 3740 (C:\Users\25538\source\java\share-liteflow\share-liteflow-web\target\classes started by 25538 in C:\Users\25538\source\java\share-liteflow)
2024-08-08 16:22:18.754|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||The following 1 profile is active: "local"
2024-08-08 16:22:18.850|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=file-server-local.yml, group=yun-demo-service] success
2024-08-08 16:22:18.851|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=user-server-local.yml, group=yun-demo-service] success
2024-08-08 16:22:18.851|main|WARN |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] config[dataId=redis-local.yml, group=yun-demo-service] is empty
2024-08-08 16:22:18.851|main|WARN |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] config[dataId=feign-local.yml, group=yun-demo-service] is empty
2024-08-08 16:22:18.851|main|WARN |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] config[dataId=mysql-local.yml, group=yun-demo-service] is empty
2024-08-08 16:22:19.534|main|ERROR|o.s.boot.SpringApplication.reportFailure:821|IGNORE|||||||||||||||||||||||||||||Application run failed
j.lang.IllegalStateException: Service id not legal hostname (${file-server})
	at o.springframework.util.Assert.state(Assert.java:76)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:111)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:282)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:270)
	at o.s.c.o.FeignClientsRegistrar.getContextId(FeignClientsRegistrar.java:288)
	at o.s.c.o.FeignClientsRegistrar.registerFeignClient(FeignClientsRegistrar.java:213)
	at o.s.c.o.FeignClientsRegistrar.registerFeignClients(FeignClientsRegistrar.java:202)
	at o.s.c.o.FeignClientsRegistrar.registerBeanDefinitions(FeignClientsRegistrar.java:151)
	at o.s.c.a.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86)
	at o.s.c.a.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396)
	... 15 frames truncated
2024-08-08 16:22:19.538|Thread-4|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Start destroying common HttpClient
2024-08-08 16:22:19.538|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.?:?|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Start destroying Publisher
2024-08-08 16:22:19.538|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.shutdown:153|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Destruction of the end
2024-08-08 16:22:19.539|Thread-4|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Destruction of the end
2024-08-08 16:54:36.617|background-preinit|INFO |o.h.v.internal.util.Version.?:21|IGNORE|||||||||||||||||||||||||||||HV000001: Hibernate Validator 6.2.5.Final
2024-08-08 16:54:36.644|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Starting Application using Java 1.8.0_421 on DESKTOP-0D3FQF2 with PID 27360 (C:\Users\25538\source\java\share-liteflow\share-liteflow-web\target\classes started by 25538 in C:\Users\25538\source\java\share-liteflow)
2024-08-08 16:54:36.645|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||The following 1 profile is active: "local"
2024-08-08 16:54:36.730|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=file-server-local.yml, group=yun-demo-service] success
2024-08-08 16:54:36.730|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=user-server-local.yml, group=yun-demo-service] success
2024-08-08 16:54:36.730|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=redis-local.yml, group=yun-demo-service] success
2024-08-08 16:54:36.731|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=feign-local.yml, group=yun-demo-service] success
2024-08-08 16:54:36.731|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=mysql-local.yml, group=yun-demo-service] success
2024-08-08 16:54:37.353|main|ERROR|o.s.boot.SpringApplication.?:?|IGNORE|||||||||||||||||||||||||||||Application run failed
j.lang.IllegalStateException: Service id not legal hostname (${file-server})
	at o.springframework.util.Assert.state(Assert.java:76)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:111)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:282)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:270)
	at o.s.c.o.FeignClientsRegistrar.getContextId(FeignClientsRegistrar.java:288)
	at o.s.c.o.FeignClientsRegistrar.registerFeignClient(FeignClientsRegistrar.java:213)
	at o.s.c.o.FeignClientsRegistrar.registerFeignClients(FeignClientsRegistrar.java:202)
	at o.s.c.o.FeignClientsRegistrar.registerBeanDefinitions(FeignClientsRegistrar.java:151)
	at o.s.c.a.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86)
	at o.s.c.a.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396)
	... 15 frames truncated
2024-08-08 16:54:37.357|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.?:?|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Start destroying Publisher
2024-08-08 16:54:37.358|Thread-4|WARN |c.a.n.c.h.HttpClientBeanHolder.shutdown:108|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Start destroying common HttpClient
2024-08-08 16:54:37.358|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.shutdown:153|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Destruction of the end
2024-08-08 16:54:37.358|Thread-4|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Destruction of the end
2024-08-08 16:56:52.341|background-preinit|INFO |o.h.v.internal.util.Version.?:?|IGNORE|||||||||||||||||||||||||||||HV000001: Hibernate Validator 6.2.5.Final
2024-08-08 16:56:52.373|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Starting Application using Java 1.8.0_421 on DESKTOP-0D3FQF2 with PID 27800 (C:\Users\25538\source\java\share-liteflow\share-liteflow-web\target\classes started by 25538 in C:\Users\25538\source\java\share-liteflow)
2024-08-08 16:56:52.373|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||The following 1 profile is active: "local"
2024-08-08 16:56:52.469|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=file-server-local.yml, group=yun-demo-service] success
2024-08-08 16:56:52.469|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=user-server-local.yml, group=yun-demo-service] success
2024-08-08 16:56:52.469|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=redis-local.yml, group=yun-demo-service] success
2024-08-08 16:56:52.469|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=feign-local.yml, group=yun-demo-service] success
2024-08-08 16:56:52.469|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=mysql-local.yml, group=yun-demo-service] success
2024-08-08 16:56:53.291|main|ERROR|o.s.boot.SpringApplication.?:?|IGNORE|||||||||||||||||||||||||||||Application run failed
j.lang.IllegalStateException: Service id not legal hostname (${user-server})
	at o.springframework.util.Assert.state(Assert.java:76)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:111)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:282)
	at o.s.c.o.FeignClientsRegistrar.getName(FeignClientsRegistrar.java:270)
	at o.s.c.o.FeignClientsRegistrar.getContextId(FeignClientsRegistrar.java:288)
	at o.s.c.o.FeignClientsRegistrar.registerFeignClient(FeignClientsRegistrar.java:213)
	at o.s.c.o.FeignClientsRegistrar.registerFeignClients(FeignClientsRegistrar.java:202)
	at o.s.c.o.FeignClientsRegistrar.registerBeanDefinitions(FeignClientsRegistrar.java:151)
	at o.s.c.a.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86)
	at o.s.c.a.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:396)
	... 15 frames truncated
2024-08-08 16:56:53.295|Thread-4|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Start destroying common HttpClient
2024-08-08 16:56:53.295|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.shutdown:136|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Start destroying Publisher
2024-08-08 16:56:53.296|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.shutdown:153|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Destruction of the end
2024-08-08 16:56:53.296|Thread-4|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Destruction of the end
2024-08-08 16:57:17.918|background-preinit|INFO |o.h.v.internal.util.Version.?:21|IGNORE|||||||||||||||||||||||||||||HV000001: Hibernate Validator 6.2.5.Final
2024-08-08 16:57:17.946|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Starting Application using Java 1.8.0_421 on DESKTOP-0D3FQF2 with PID 13100 (C:\Users\25538\source\java\share-liteflow\share-liteflow-web\target\classes started by 25538 in C:\Users\25538\source\java\share-liteflow)
2024-08-08 16:57:17.947|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||The following 1 profile is active: "local"
2024-08-08 16:57:18.028|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=file-server-local.yml, group=yun-demo-service] success
2024-08-08 16:57:18.029|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=user-server-local.yml, group=yun-demo-service] success
2024-08-08 16:57:18.029|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=redis-local.yml, group=yun-demo-service] success
2024-08-08 16:57:18.029|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=feign-local.yml, group=yun-demo-service] success
2024-08-08 16:57:18.029|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=mysql-local.yml, group=yun-demo-service] success
2024-08-08 16:57:19.509|main|INFO |o.s.c.a.ConfigurationClassPostProcessor.?:?|IGNORE|||||||||||||||||||||||||||||Cannot enhance @Configuration bean definition 'com.yomahub.liteflow.springboot.config.LiteflowMainAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2024-08-08 16:57:19.594|main|INFO |o.s.c.c.scope.GenericScope.?:?|IGNORE|||||||||||||||||||||||||||||BeanFactory id=c636b971-04c8-3b71-a36d-1bf4fc70b07d
2024-08-08 16:57:19.947|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'com.yomahub.liteflow.springboot.config.LiteflowPropertyAutoConfiguration' of type [com.yomahub.liteflow.springboot.config.LiteflowPropertyAutoConfiguration$$EnhancerBySpringCGLIB$$aa4fc340] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 16:57:19.963|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration' of type [org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 16:57:19.967|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 16:57:19.970|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'loadBalancerClientsDefaultsMappingsProvider' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration$$Lambda$494/0x00000007c06bb428] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 16:57:19.975|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'defaultsBindHandlerAdvisor' of type [org.springframework.cloud.commons.config.DefaultsBindHandlerAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 16:57:19.987|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflow-com.yomahub.liteflow.springboot.LiteflowProperty' of type [com.yomahub.liteflow.springboot.LiteflowProperty] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 16:57:19.996|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflow.monitor-com.yomahub.liteflow.springboot.LiteflowMonitorProperty' of type [com.yomahub.liteflow.springboot.LiteflowMonitorProperty] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 16:57:20.005|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflowConfig' of type [com.yomahub.liteflow.property.LiteflowConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 16:57:20.012|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'com.yomahub.liteflow.spi.spring.SpringAware' of type [com.yomahub.liteflow.spi.spring.SpringAware] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 16:57:20.018|main|INFO |c.y.liteflow.util.LOGOPrinter.?:?|IGNORE|||||||||||||||||||||||||||||
================================================================================================
		 _     ___ _____ _____      _____ _     _____        __
		| |   |_ _|_   _| ____|    |  ___| |   / _ \ \      / /
		| |    | |  | | |  _| _____| |_  | |  | | | \ \ /\ / / 
		| |___ | |  | | | |__|_____|  _| | |__| |_| |\ V  V /  
		|_____|___| |_| |_____|    |_|   |_____\___/  \_/\_/   

		Version: 2.12.2
		Make your code amazing.
		website：https://liteflow.cc
		wechat：bryan_31
================================================================================================

2024-08-08 16:57:20.348|main|INFO |o.s.b.w.e.t.TomcatWebServer.?:?|IGNORE|||||||||||||||||||||||||||||Tomcat initialized with port(s): 8083 (http)
2024-08-08 16:57:20.360|main|INFO |o.a.c.http11.Http11NioProtocol.?:?|IGNORE|||||||||||||||||||||||||||||Initializing ProtocolHandler ["http-nio-8083"]
2024-08-08 16:57:20.360|main|INFO |o.a.c.core.StandardService.?:?|IGNORE|||||||||||||||||||||||||||||Starting service [Tomcat]
2024-08-08 16:57:20.361|main|INFO |o.a.c.core.StandardEngine.log:173|IGNORE|||||||||||||||||||||||||||||Starting Servlet engine: [Apache Tomcat/9.0.75]
2024-08-08 16:57:20.556|main|INFO |o.a.c.c.C.[.[localhost].[/yun].?:?|IGNORE|||||||||||||||||||||||||||||Initializing Spring embedded WebApplicationContext
2024-08-08 16:57:20.557|main|INFO |o.s.b.w.s.c.ServletWebServerApplicationContext.?:?|IGNORE|||||||||||||||||||||||||||||Root WebApplicationContext: initialization completed in 2525 ms
2024-08-08 16:57:20.654|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Running with Spring profile(s) :[local] 
2024-08-08 16:57:21.636|main|INFO |c.a.d.s.b.a.DruidDataSourceAutoConfigure.?:?|IGNORE|||||||||||||||||||||||||||||Init DruidDataSource
2024-08-08 16:57:22.108|main|INFO |c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} inited
2024-08-08 16:57:22.321|main|WARN |c.b.m.c.i.AbstractMethod.?:?|IGNORE|||||||||||||||||||||||||||||[com.zyhl.yun.liteflow.persistence.mapper.DemoItemMapper.selectList] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectList]
2024-08-08 16:57:22.335|main|WARN |c.b.m.c.m.TableInfoHelper.?:?|IGNORE|||||||||||||||||||||||||||||Can not find table primary key in Class: "com.zyhl.yun.liteflow.persistence.mapper.DemoMapper".
2024-08-08 16:57:23.274|main|INFO |o.s.c.o.FeignClientFactoryBean.?:?|IGNORE|||||||||||||||||||||||||||||For 'file-server' URL not provided. Will try picking an instance via load-balancing.
2024-08-08 16:57:23.288|main|INFO |c.y.l.spring.ComponentScanner.?:?|IGNORE|||||||||||||||||||||||||||||component[assetsInfo] has been found
2024-08-08 16:57:23.292|main|INFO |c.y.l.spring.ComponentScanner.?:?|IGNORE|||||||||||||||||||||||||||||component[assetsValidate] has been found
2024-08-08 16:57:23.294|main|WARN |o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext.?:?|IGNORE|||||||||||||||||||||||||||||Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'benefitValidate' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-application\target\classes\com\zyhl\yun\liteflow\application\cmp\BenefitValidateNode.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
2024-08-08 16:57:23.294|main|INFO |c.a.druid.pool.DruidDataSource.close:2073|IGNORE|||||||||||||||||||||||||||||{dataSource-1} closing ...
2024-08-08 16:57:23.300|main|INFO |c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} closed
2024-08-08 16:57:23.303|main|INFO |o.a.c.core.StandardService.?:?|IGNORE|||||||||||||||||||||||||||||Stopping service [Tomcat]
2024-08-08 16:57:23.315|main|INFO |o.s.b.a.l.ConditionEvaluationReportLoggingListener.?:?|IGNORE|||||||||||||||||||||||||||||

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-08-08 16:57:23.341|main|ERROR|o.s.boot.SpringApplication.?:?|IGNORE|||||||||||||||||||||||||||||Application run failed
o.s.b.f.BeanCreationException: Error creating bean with name 'benefitValidate' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-application\target\classes\com\zyhl\yun\liteflow\application\cmp\BenefitValidateNode.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at o.s.b.f.s.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at o.s.b.f.s.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at o.s.b.f.s.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at o.s.b.f.s.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at o.s.b.f.s.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at o.s.c.s.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	... 6 frames truncated
Caused by: o.s.b.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at o.s.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at o.s.b.f.s.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
	... 15 common frames omitted
Caused by: java.lang.NullPointerException: null
	at c.y.l.core.NodeComponent.getSlotIndex(NodeComponent.java:246)
	at c.y.l.core.NodeComponent.getSlot(NodeComponent.java:250)
	at c.y.l.core.NodeComponent.getContextBean(NodeComponent.java:258)
	at c.z.y.l.a.c.BenefitValidateNode.<init>(BenefitValidateNode.java:12)
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at o.s.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 17 common frames omitted
2024-08-08 17:03:32.269|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.shutdown:136|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Start destroying Publisher
2024-08-08 17:03:32.269|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.shutdown:153|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Destruction of the end
2024-08-08 17:03:32.269|Thread-4|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Start destroying common HttpClient
2024-08-08 17:03:32.269|Thread-4|WARN |c.a.n.c.h.HttpClientBeanHolder.shutdown:114|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Destruction of the end
2024-08-08 17:03:46.173|background-preinit|INFO |o.h.v.internal.util.Version.?:?|IGNORE|||||||||||||||||||||||||||||HV000001: Hibernate Validator 6.2.5.Final
2024-08-08 17:03:46.203|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Starting Application using Java 1.8.0_421 on DESKTOP-0D3FQF2 with PID 27948 (C:\Users\25538\source\java\share-liteflow\share-liteflow-web\target\classes started by 25538 in C:\Users\25538\source\java\share-liteflow)
2024-08-08 17:03:46.204|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||The following 1 profile is active: "local"
2024-08-08 17:03:46.308|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=file-server-local.yml, group=yun-demo-service] success
2024-08-08 17:03:46.309|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=user-server-local.yml, group=yun-demo-service] success
2024-08-08 17:03:46.309|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=redis-local.yml, group=yun-demo-service] success
2024-08-08 17:03:46.309|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=feign-local.yml, group=yun-demo-service] success
2024-08-08 17:03:46.310|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=mysql-local.yml, group=yun-demo-service] success
2024-08-08 17:03:47.645|main|INFO |o.s.c.a.ConfigurationClassPostProcessor.?:?|IGNORE|||||||||||||||||||||||||||||Cannot enhance @Configuration bean definition 'com.yomahub.liteflow.springboot.config.LiteflowMainAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2024-08-08 17:03:47.742|main|INFO |o.s.c.c.scope.GenericScope.?:?|IGNORE|||||||||||||||||||||||||||||BeanFactory id=c636b971-04c8-3b71-a36d-1bf4fc70b07d
2024-08-08 17:03:48.153|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'com.yomahub.liteflow.springboot.config.LiteflowPropertyAutoConfiguration' of type [com.yomahub.liteflow.springboot.config.LiteflowPropertyAutoConfiguration$$EnhancerBySpringCGLIB$$612f1e75] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 17:03:48.175|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration' of type [org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 17:03:48.181|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 17:03:48.184|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'loadBalancerClientsDefaultsMappingsProvider' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration$$Lambda$494/0x00000007c06bb428] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 17:03:48.194|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'defaultsBindHandlerAdvisor' of type [org.springframework.cloud.commons.config.DefaultsBindHandlerAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 17:03:48.211|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflow-com.yomahub.liteflow.springboot.LiteflowProperty' of type [com.yomahub.liteflow.springboot.LiteflowProperty] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 17:03:48.223|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflow.monitor-com.yomahub.liteflow.springboot.LiteflowMonitorProperty' of type [com.yomahub.liteflow.springboot.LiteflowMonitorProperty] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 17:03:48.234|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflowConfig' of type [com.yomahub.liteflow.property.LiteflowConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 17:03:48.243|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'com.yomahub.liteflow.spi.spring.SpringAware' of type [com.yomahub.liteflow.spi.spring.SpringAware] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-08 17:03:48.250|main|INFO |c.y.liteflow.util.LOGOPrinter.?:?|IGNORE|||||||||||||||||||||||||||||
================================================================================================
		 _     ___ _____ _____      _____ _     _____        __
		| |   |_ _|_   _| ____|    |  ___| |   / _ \ \      / /
		| |    | |  | | |  _| _____| |_  | |  | | | \ \ /\ / / 
		| |___ | |  | | | |__|_____|  _| | |__| |_| |\ V  V /  
		|_____|___| |_| |_____|    |_|   |_____\___/  \_/\_/   

		Version: 2.12.2
		Make your code amazing.
		website：https://liteflow.cc
		wechat：bryan_31
================================================================================================

2024-08-08 17:03:48.580|main|INFO |o.s.b.w.e.t.TomcatWebServer.?:?|IGNORE|||||||||||||||||||||||||||||Tomcat initialized with port(s): 8083 (http)
2024-08-08 17:03:48.590|main|INFO |o.a.c.http11.Http11NioProtocol.?:?|IGNORE|||||||||||||||||||||||||||||Initializing ProtocolHandler ["http-nio-8083"]
2024-08-08 17:03:48.590|main|INFO |o.a.c.core.StandardService.?:?|IGNORE|||||||||||||||||||||||||||||Starting service [Tomcat]
2024-08-08 17:03:48.591|main|INFO |o.a.c.core.StandardEngine.log:173|IGNORE|||||||||||||||||||||||||||||Starting Servlet engine: [Apache Tomcat/9.0.75]
2024-08-08 17:03:48.770|main|INFO |o.a.c.c.C.[.[localhost].[/yun].?:?|IGNORE|||||||||||||||||||||||||||||Initializing Spring embedded WebApplicationContext
2024-08-08 17:03:48.770|main|INFO |o.s.b.w.s.c.ServletWebServerApplicationContext.?:?|IGNORE|||||||||||||||||||||||||||||Root WebApplicationContext: initialization completed in 2456 ms
2024-08-08 17:03:48.866|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Running with Spring profile(s) :[local] 
2024-08-08 17:03:49.877|main|INFO |c.a.d.s.b.a.DruidDataSourceAutoConfigure.?:?|IGNORE|||||||||||||||||||||||||||||Init DruidDataSource
2024-08-08 17:03:50.313|main|INFO |c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} inited
2024-08-08 17:03:50.554|main|WARN |c.b.m.c.i.AbstractMethod.?:?|IGNORE|||||||||||||||||||||||||||||[com.zyhl.yun.liteflow.persistence.mapper.DemoItemMapper.selectList] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectList]
2024-08-08 17:03:50.566|main|WARN |c.b.m.c.m.TableInfoHelper.?:?|IGNORE|||||||||||||||||||||||||||||Can not find table primary key in Class: "com.zyhl.yun.liteflow.persistence.mapper.DemoMapper".
2024-08-08 17:03:51.547|main|INFO |o.s.c.o.FeignClientFactoryBean.?:?|IGNORE|||||||||||||||||||||||||||||For 'file-server' URL not provided. Will try picking an instance via load-balancing.
2024-08-08 17:03:51.563|main|INFO |c.y.l.spring.ComponentScanner.?:?|IGNORE|||||||||||||||||||||||||||||component[assetsInfo] has been found
2024-08-08 17:03:51.567|main|INFO |c.y.l.spring.ComponentScanner.?:?|IGNORE|||||||||||||||||||||||||||||component[assetsValidate] has been found
2024-08-08 17:03:51.570|main|WARN |o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext.?:?|IGNORE|||||||||||||||||||||||||||||Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'benefitValidate' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-application\target\classes\com\zyhl\yun\liteflow\application\cmp\BenefitValidateNode.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
2024-08-08 17:03:51.570|main|INFO |c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} closing ...
2024-08-08 17:03:51.576|main|INFO |c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} closed
2024-08-08 17:03:51.578|main|INFO |o.a.c.core.StandardService.?:?|IGNORE|||||||||||||||||||||||||||||Stopping service [Tomcat]
2024-08-08 17:03:51.594|main|INFO |o.s.b.a.l.ConditionEvaluationReportLoggingListener.?:?|IGNORE|||||||||||||||||||||||||||||

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-08-08 17:03:51.625|main|ERROR|o.s.boot.SpringApplication.reportFailure:821|IGNORE|||||||||||||||||||||||||||||Application run failed
o.s.b.f.BeanCreationException: Error creating bean with name 'benefitValidate' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-application\target\classes\com\zyhl\yun\liteflow\application\cmp\BenefitValidateNode.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at o.s.b.f.s.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at o.s.b.f.s.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at o.s.b.f.s.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at o.s.b.f.s.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at o.s.b.f.s.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at o.s.c.s.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	... 6 frames truncated
Caused by: o.s.b.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at o.s.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at o.s.b.f.s.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
	... 15 common frames omitted
Caused by: java.lang.NullPointerException: null
	at c.y.l.core.NodeComponent.getSlotIndex(NodeComponent.java:246)
	at c.y.l.core.NodeComponent.getSlot(NodeComponent.java:250)
	at c.y.l.core.NodeComponent.getContextBean(NodeComponent.java:258)
	at c.z.y.l.a.c.BenefitValidateNode.<init>(BenefitValidateNode.java:14)
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at o.s.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 17 common frames omitted
2024-08-08 17:18:00.997|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.?:?|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Start destroying Publisher
2024-08-08 17:18:00.997|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.?:?|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Destruction of the end
2024-08-08 17:18:00.997|Thread-4|WARN |c.a.n.c.h.HttpClientBeanHolder.shutdown:108|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Start destroying common HttpClient
2024-08-08 17:18:00.997|Thread-4|WARN |c.a.n.c.h.HttpClientBeanHolder.shutdown:114|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Destruction of the end
2024-08-09 15:10:09.771|background-preinit|INFO |o.h.v.internal.util.Version.?:?|IGNORE|||||||||||||||||||||||||||||HV000001: Hibernate Validator 6.2.5.Final
2024-08-09 15:10:09.790|main|INFO |c.z.yun.liteflow.Application.?:55|IGNORE|||||||||||||||||||||||||||||Starting Application using Java 1.8.0_421 on DESKTOP-0D3FQF2 with PID 26020 (C:\Users\25538\source\java\share-liteflow\share-liteflow-web\target\classes started by 25538 in C:\Users\25538\source\java\share-liteflow)
2024-08-09 15:10:09.791|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||The following 1 profile is active: "local"
2024-08-09 15:10:09.827|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=file-server-local.yml, group=yun-demo-service] success
2024-08-09 15:10:09.827|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=user-server-local.yml, group=yun-demo-service] success
2024-08-09 15:10:09.828|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=redis-local.yml, group=yun-demo-service] success
2024-08-09 15:10:09.828|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=feign-local.yml, group=yun-demo-service] success
2024-08-09 15:10:09.828|main|INFO |c.a.c.n.c.NacosConfigDataLoader.logTo:255|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=mysql-local.yml, group=yun-demo-service] success
2024-08-09 15:10:09.884|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.?:?|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:10.908|main|INFO |o.s.c.a.ConfigurationClassPostProcessor.enhanceConfigurationClasses:426|IGNORE|||||||||||||||||||||||||||||Cannot enhance @Configuration bean definition 'com.yomahub.liteflow.springboot.config.LiteflowMainAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2024-08-09 15:10:10.967|main|INFO |o.s.c.c.scope.GenericScope.?:283|IGNORE|||||||||||||||||||||||||||||BeanFactory id=9de98e0d-ac3e-3863-9242-41f1a4fdf211
2024-08-09 15:10:11.235|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:376|IGNORE|||||||||||||||||||||||||||||Bean 'com.yomahub.liteflow.springboot.config.LiteflowPropertyAutoConfiguration' of type [com.yomahub.liteflow.springboot.config.LiteflowPropertyAutoConfiguration$$EnhancerBySpringCGLIB$$38f69466] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:10:11.247|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration' of type [org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:10:11.250|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:10:11.252|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'loadBalancerClientsDefaultsMappingsProvider' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration$$Lambda$494/0x00000007c0695c28] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:10:11.255|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:376|IGNORE|||||||||||||||||||||||||||||Bean 'defaultsBindHandlerAdvisor' of type [org.springframework.cloud.commons.config.DefaultsBindHandlerAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:10:11.264|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflow-com.yomahub.liteflow.springboot.LiteflowProperty' of type [com.yomahub.liteflow.springboot.LiteflowProperty] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:10:11.269|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflow.monitor-com.yomahub.liteflow.springboot.LiteflowMonitorProperty' of type [com.yomahub.liteflow.springboot.LiteflowMonitorProperty] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:10:11.276|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflowConfig' of type [com.yomahub.liteflow.property.LiteflowConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:10:11.281|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'com.yomahub.liteflow.spi.spring.SpringAware' of type [com.yomahub.liteflow.spi.spring.SpringAware] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:10:11.286|main|INFO |c.y.liteflow.util.LOGOPrinter.?:?|IGNORE|||||||||||||||||||||||||||||
================================================================================================
		 _     ___ _____ _____      _____ _     _____        __
		| |   |_ _|_   _| ____|    |  ___| |   / _ \ \      / /
		| |    | |  | | |  _| _____| |_  | |  | | | \ \ /\ / / 
		| |___ | |  | | | |__|_____|  _| | |__| |_| |\ V  V /  
		|_____|___| |_| |_____|    |_|   |_____\___/  \_/\_/   

		Version: 2.12.2
		Make your code amazing.
		website：https://liteflow.cc
		wechat：bryan_31
================================================================================================

2024-08-09 15:10:11.523|main|INFO |o.s.b.w.e.t.TomcatWebServer.?:?|IGNORE|||||||||||||||||||||||||||||Tomcat initialized with port(s): 8083 (http)
2024-08-09 15:10:11.535|main|INFO |o.a.c.http11.Http11NioProtocol.?:?|IGNORE|||||||||||||||||||||||||||||Initializing ProtocolHandler ["http-nio-8083"]
2024-08-09 15:10:11.535|main|INFO |o.a.c.core.StandardService.log:173|IGNORE|||||||||||||||||||||||||||||Starting service [Tomcat]
2024-08-09 15:10:11.535|main|INFO |o.a.c.core.StandardEngine.log:173|IGNORE|||||||||||||||||||||||||||||Starting Servlet engine: [Apache Tomcat/9.0.75]
2024-08-09 15:10:11.643|main|INFO |o.a.c.c.C.[.[localhost].[/yun].?:?|IGNORE|||||||||||||||||||||||||||||Initializing Spring embedded WebApplicationContext
2024-08-09 15:10:11.644|main|INFO |o.s.b.w.s.c.ServletWebServerApplicationContext.?:?|IGNORE|||||||||||||||||||||||||||||Root WebApplicationContext: initialization completed in 1814 ms
2024-08-09 15:10:11.701|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Running with Spring profile(s) :[local] 
2024-08-09 15:10:12.015|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.?:?|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:12.015|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 1 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:12.385|main|INFO |c.a.d.s.b.a.DruidDataSourceAutoConfigure.?:?|IGNORE|||||||||||||||||||||||||||||Init DruidDataSource
2024-08-09 15:10:12.745|main|INFO |c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} inited
2024-08-09 15:10:12.891|main|WARN |c.b.m.c.i.AbstractMethod.?:?|IGNORE|||||||||||||||||||||||||||||[com.zyhl.yun.liteflow.persistence.mapper.DemoItemMapper.selectList] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectList]
2024-08-09 15:10:12.899|main|WARN |c.b.m.c.m.TableInfoHelper.?:?|IGNORE|||||||||||||||||||||||||||||Can not find table primary key in Class: "com.zyhl.yun.liteflow.persistence.mapper.DemoMapper".
2024-08-09 15:10:13.495|main|INFO |o.s.c.o.FeignClientFactoryBean.?:?|IGNORE|||||||||||||||||||||||||||||For 'file-server' URL not provided. Will try picking an instance via load-balancing.
2024-08-09 15:10:13.505|main|INFO |c.y.l.spring.ComponentScanner.?:?|IGNORE|||||||||||||||||||||||||||||component[assetsInfo] has been found
2024-08-09 15:10:13.507|main|INFO |c.y.l.spring.ComponentScanner.postProcessAfterInitialization:96|IGNORE|||||||||||||||||||||||||||||component[assetsValidate] has been found
2024-08-09 15:10:13.508|main|WARN |o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext.?:?|IGNORE|||||||||||||||||||||||||||||Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'benefitValidate' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-application\target\classes\com\zyhl\yun\liteflow\application\cmp\BenefitValidateNode.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
2024-08-09 15:10:13.509|main|INFO |c.a.druid.pool.DruidDataSource.close:2073|IGNORE|||||||||||||||||||||||||||||{dataSource-1} closing ...
2024-08-09 15:10:13.513|main|INFO |c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} closed
2024-08-09 15:10:13.516|main|INFO |o.a.c.core.StandardService.log:173|IGNORE|||||||||||||||||||||||||||||Stopping service [Tomcat]
2024-08-09 15:10:13.525|main|INFO |o.s.b.a.l.ConditionEvaluationReportLoggingListener.?:?|IGNORE|||||||||||||||||||||||||||||

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-08-09 15:10:13.543|main|ERROR|o.s.boot.SpringApplication.?:?|IGNORE|||||||||||||||||||||||||||||Application run failed
o.s.b.f.BeanCreationException: Error creating bean with name 'benefitValidate' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-application\target\classes\com\zyhl\yun\liteflow\application\cmp\BenefitValidateNode.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at o.s.b.f.s.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at o.s.b.f.s.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at o.s.b.f.s.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at o.s.b.f.s.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at o.s.b.f.s.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at o.s.c.s.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	... 6 frames truncated
Caused by: o.s.b.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at o.s.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at o.s.b.f.s.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
	... 15 common frames omitted
Caused by: java.lang.NullPointerException: null
	at c.y.l.core.NodeComponent.getSlotIndex(NodeComponent.java:246)
	at c.y.l.core.NodeComponent.getSlot(NodeComponent.java:250)
	at c.y.l.core.NodeComponent.getContextBean(NodeComponent.java:258)
	at c.z.y.l.a.c.BenefitValidateNode.<init>(BenefitValidateNode.java:14)
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at o.s.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 17 common frames omitted
2024-08-09 15:10:14.249|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.?:?|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:14.250|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 2 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:16.619|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:16.620|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:60|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 3 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:19.039|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:19.040|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 4 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:21.597|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:21.598|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 5 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:24.236|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:24.237|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 6 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:26.995|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:26.996|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 7 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:29.859|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:29.859|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 8 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:32.805|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.?:?|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:32.805|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 9 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:35.863|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:35.863|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 10 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:39.030|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:39.031|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 11 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:42.281|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.?:?|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:42.282|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 12 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:45.658|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:45.659|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.printIfInfoEnabled:60|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 13 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:49.129|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.?:?|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:49.129|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 14 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:52.677|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:52.678|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.printIfInfoEnabled:60|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 15 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:10:56.318|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:10:56.318|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 16 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:11:00.068|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:11:00.068|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 17 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:11:03.901|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.?:?|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:11:03.902|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 18 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:11:07.854|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:11:07.855|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 19 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:11:11.906|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:11:11.906|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 20 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:11:16.040|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.?:?|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-09 15:11:16.041|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.printIfInfoEnabled:60|IGNORE|||||||||||||||||||||||||||||[aebed841-7daf-4bd1-80f8-aa1980ea97fe_config-0] Fail to connect server, after trying 21 times, last try server is {serverIp = '192.168.71.1', server main port = 8848}, error = unknown
2024-08-09 15:11:20.072|Thread-3|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Start destroying common HttpClient
2024-08-09 15:11:20.072|Thread-7|WARN |c.a.n.c.notify.NotifyCenter.shutdown:136|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Start destroying Publisher
2024-08-09 15:11:20.072|Thread-7|WARN |c.a.n.c.notify.NotifyCenter.shutdown:153|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Destruction of the end
2024-08-09 15:11:20.073|Thread-3|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Destruction of the end
2024-08-09 15:11:29.106|background-preinit|INFO |o.h.v.internal.util.Version.?:?|IGNORE|||||||||||||||||||||||||||||HV000001: Hibernate Validator 6.2.5.Final
2024-08-09 15:11:29.125|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Starting Application using Java 1.8.0_421 on DESKTOP-0D3FQF2 with PID 6188 (C:\Users\25538\source\java\share-liteflow\share-liteflow-web\target\classes started by 25538 in C:\Users\25538\source\java\share-liteflow)
2024-08-09 15:11:29.126|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||The following 1 profile is active: "local"
2024-08-09 15:11:29.222|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=file-server-local.yml, group=yun-demo-service] success
2024-08-09 15:11:29.222|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=user-server-local.yml, group=yun-demo-service] success
2024-08-09 15:11:29.222|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=redis-local.yml, group=yun-demo-service] success
2024-08-09 15:11:29.222|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=feign-local.yml, group=yun-demo-service] success
2024-08-09 15:11:29.223|main|INFO |c.a.c.n.c.NacosConfigDataLoader.?:?|IGNORE|||||||||||||||||||||||||||||[Nacos Config] Load config[dataId=mysql-local.yml, group=yun-demo-service] success
2024-08-09 15:11:29.439|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[37d5c211-7ebc-491d-a03c-c7b04339e4f7_config-0] Success to connect a server [192.168.71.1:8848], connectionId = 1723187489304_192.168.71.1_59275
2024-08-09 15:11:29.439|com.alibaba.nacos.client.remote.worker|INFO |c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||[37d5c211-7ebc-491d-a03c-c7b04339e4f7_config-0] Notify connected event to listeners.
2024-08-09 15:11:30.131|main|INFO |o.s.c.a.ConfigurationClassPostProcessor.enhanceConfigurationClasses:426|IGNORE|||||||||||||||||||||||||||||Cannot enhance @Configuration bean definition 'com.yomahub.liteflow.springboot.config.LiteflowMainAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2024-08-09 15:11:30.183|main|INFO |o.s.c.c.scope.GenericScope.setSerializationId:283|IGNORE|||||||||||||||||||||||||||||BeanFactory id=9de98e0d-ac3e-3863-9242-41f1a4fdf211
2024-08-09 15:11:30.414|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'com.yomahub.liteflow.springboot.config.LiteflowPropertyAutoConfiguration' of type [com.yomahub.liteflow.springboot.config.LiteflowPropertyAutoConfiguration$$EnhancerBySpringCGLIB$$55ae871b] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:11:30.426|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration' of type [org.springframework.cloud.commons.config.CommonsConfigAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:11:30.430|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:11:30.431|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'loadBalancerClientsDefaultsMappingsProvider' of type [org.springframework.cloud.client.loadbalancer.LoadBalancerDefaultMappingsProviderAutoConfiguration$$Lambda$494/0x00000007c06c3c28] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:11:30.435|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'defaultsBindHandlerAdvisor' of type [org.springframework.cloud.commons.config.DefaultsBindHandlerAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:11:30.443|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:376|IGNORE|||||||||||||||||||||||||||||Bean 'liteflow-com.yomahub.liteflow.springboot.LiteflowProperty' of type [com.yomahub.liteflow.springboot.LiteflowProperty] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:11:30.449|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflow.monitor-com.yomahub.liteflow.springboot.LiteflowMonitorProperty' of type [com.yomahub.liteflow.springboot.LiteflowMonitorProperty] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:11:30.455|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'liteflowConfig' of type [com.yomahub.liteflow.property.LiteflowConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:11:30.461|main|INFO |o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.?:?|IGNORE|||||||||||||||||||||||||||||Bean 'com.yomahub.liteflow.spi.spring.SpringAware' of type [com.yomahub.liteflow.spi.spring.SpringAware] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2024-08-09 15:11:30.467|main|INFO |c.y.liteflow.util.LOGOPrinter.?:?|IGNORE|||||||||||||||||||||||||||||
================================================================================================
		 _     ___ _____ _____      _____ _     _____        __
		| |   |_ _|_   _| ____|    |  ___| |   / _ \ \      / /
		| |    | |  | | |  _| _____| |_  | |  | | | \ \ /\ / / 
		| |___ | |  | | | |__|_____|  _| | |__| |_| |\ V  V /  
		|_____|___| |_| |_____|    |_|   |_____\___/  \_/\_/   

		Version: 2.12.2
		Make your code amazing.
		website：https://liteflow.cc
		wechat：bryan_31
================================================================================================

2024-08-09 15:11:30.642|main|INFO |o.s.b.w.e.t.TomcatWebServer.initialize:108|IGNORE|||||||||||||||||||||||||||||Tomcat initialized with port(s): 8083 (http)
2024-08-09 15:11:30.650|main|INFO |o.a.c.http11.Http11NioProtocol.log:173|IGNORE|||||||||||||||||||||||||||||Initializing ProtocolHandler ["http-nio-8083"]
2024-08-09 15:11:30.651|main|INFO |o.a.c.core.StandardService.log:173|IGNORE|||||||||||||||||||||||||||||Starting service [Tomcat]
2024-08-09 15:11:30.652|main|INFO |o.a.c.core.StandardEngine.?:?|IGNORE|||||||||||||||||||||||||||||Starting Servlet engine: [Apache Tomcat/9.0.75]
2024-08-09 15:11:30.766|main|INFO |o.a.c.c.C.[.[localhost].[/yun].?:?|IGNORE|||||||||||||||||||||||||||||Initializing Spring embedded WebApplicationContext
2024-08-09 15:11:30.766|main|INFO |o.s.b.w.s.c.ServletWebServerApplicationContext.?:?|IGNORE|||||||||||||||||||||||||||||Root WebApplicationContext: initialization completed in 1541 ms
2024-08-09 15:11:30.828|main|INFO |c.z.yun.liteflow.Application.?:?|IGNORE|||||||||||||||||||||||||||||Running with Spring profile(s) :[local] 
2024-08-09 15:11:31.654|main|INFO |c.a.d.s.b.a.DruidDataSourceAutoConfigure.?:?|IGNORE|||||||||||||||||||||||||||||Init DruidDataSource
2024-08-09 15:11:31.847|main|INFO |c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} inited
2024-08-09 15:11:31.997|main|WARN |c.b.m.c.i.AbstractMethod.?:?|IGNORE|||||||||||||||||||||||||||||[com.zyhl.yun.liteflow.persistence.mapper.DemoItemMapper.selectList] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectList]
2024-08-09 15:11:32.007|main|WARN |c.b.m.c.m.TableInfoHelper.?:?|IGNORE|||||||||||||||||||||||||||||Can not find table primary key in Class: "com.zyhl.yun.liteflow.persistence.mapper.DemoMapper".
2024-08-09 15:11:32.629|main|INFO |o.s.c.o.FeignClientFactoryBean.?:?|IGNORE|||||||||||||||||||||||||||||For 'file-server' URL not provided. Will try picking an instance via load-balancing.
2024-08-09 15:11:32.640|main|INFO |c.y.l.spring.ComponentScanner.?:?|IGNORE|||||||||||||||||||||||||||||component[assetsInfo] has been found
2024-08-09 15:11:32.642|main|INFO |c.y.l.spring.ComponentScanner.?:?|IGNORE|||||||||||||||||||||||||||||component[assetsValidate] has been found
2024-08-09 15:11:32.643|main|WARN |o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext.refresh:591|IGNORE|||||||||||||||||||||||||||||Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'benefitValidate' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-application\target\classes\com\zyhl\yun\liteflow\application\cmp\BenefitValidateNode.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
2024-08-09 15:11:32.644|main|INFO |c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} closing ...
2024-08-09 15:11:32.647|main|INFO |c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} closed
2024-08-09 15:11:32.650|main|INFO |o.a.c.core.StandardService.log:173|IGNORE|||||||||||||||||||||||||||||Stopping service [Tomcat]
2024-08-09 15:11:32.660|main|INFO |o.s.b.a.l.ConditionEvaluationReportLoggingListener.?:?|IGNORE|||||||||||||||||||||||||||||

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-08-09 15:11:32.675|main|ERROR|o.s.boot.SpringApplication.?:?|IGNORE|||||||||||||||||||||||||||||Application run failed
o.s.b.f.BeanCreationException: Error creating bean with name 'benefitValidate' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-application\target\classes\com\zyhl\yun\liteflow\application\cmp\BenefitValidateNode.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at o.s.b.f.s.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at o.s.b.f.s.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at o.s.b.f.s.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at o.s.b.f.s.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at o.s.b.f.s.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at o.s.c.s.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	... 6 frames truncated
Caused by: o.s.b.BeanInstantiationException: Failed to instantiate [com.zyhl.yun.liteflow.application.cmp.BenefitValidateNode]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at o.s.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at o.s.b.f.s.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
	... 15 common frames omitted
Caused by: java.lang.NullPointerException: null
	at c.y.l.core.NodeComponent.getSlotIndex(NodeComponent.java:246)
	at c.y.l.core.NodeComponent.getSlot(NodeComponent.java:250)
	at c.y.l.core.NodeComponent.getContextBean(NodeComponent.java:258)
	at c.z.y.l.a.c.BenefitValidateNode.<init>(BenefitValidateNode.java:14)
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at o.s.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 17 common frames omitted
2024-08-09 15:12:11.460|Thread-3|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Start destroying common HttpClient
2024-08-09 15:12:11.460|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.shutdown:136|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Start destroying Publisher
2024-08-09 15:12:11.461|Thread-8|WARN |c.a.n.c.notify.NotifyCenter.shutdown:153|IGNORE|||||||||||||||||||||||||||||[NotifyCenter] Destruction of the end
2024-08-09 15:12:11.462|Thread-3|WARN |c.a.n.c.h.HttpClientBeanHolder.?:?|IGNORE|||||||||||||||||||||||||||||[HttpClientBeanHolder] Destruction of the end
