2024-08-10 09:32:18.436|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-10 09:32:20.568|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-10 09:32:22.802|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-10 09:32:25.162|com.alibaba.nacos.client.remote.worker|ERROR|c.a.n.c.r.c.grpc.GrpcClient.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Server check fail, please check server 192.168.71.1 ,port 9848 is available , error ={}
j.u.c.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.s.c.g.c.u.c.AbstractFuture.getDoneValue(AbstractFuture.java:566)
	at c.a.n.s.c.g.c.u.c.AbstractFuture.get(AbstractFuture.java:445)
	at c.a.n.c.r.c.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at c.a.n.c.r.c.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at c.a.n.c.r.client.RpcClient.reconnect(RpcClient.java:522)
	at c.a.n.c.r.client.RpcClient.lambda$start$2(RpcClient.java:370)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:511)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 frames truncated
Caused by: c.a.n.s.i.g.StatusRuntimeException: UNAVAILABLE: io exception
	at c.a.n.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at c.a.n.s.i.g.s.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at c.a.n.s.i.g.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at c.a.n.s.i.g.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at c.a.n.s.i.g.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at c.a.n.s.i.g.i.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	... 8 frames truncated
	... 3 common frames omitted
Caused by: c.a.n.s.i.g.n.s.i.n.c.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.71.1:9848
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
	at c.a.n.s.i.g.n.s.i.n.c.s.n.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at c.a.n.s.i.g.n.s.i.n.c.n.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKey(NioEventLoop.java:685)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at c.a.n.s.i.g.n.s.i.n.c.n.NioEventLoop.run(NioEventLoop.java:511)
	at c.a.n.s.i.g.n.s.i.n.u.c.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at c.a.n.s.i.g.n.s.i.n.u.i.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 2 frames truncated
2024-08-10 09:32:25.317|main|ERROR|c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||init datasource error, url: jdbc:p6spy:mysql://127.0.0.1:3306/share?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
j.s.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at c.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at c.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at c.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at c.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at c.m.c.j.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	... 110 frames truncated
Caused by: c.m.cj.exceptions.CJException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:105)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:151)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:124)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:153)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
	... 5 frames truncated
	... 114 common frames omitted
Caused by: c.m.c.e.UnableToConnectException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:85)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130)
	... 120 common frames omitted
2024-08-10 09:32:25.322|main|ERROR|c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} init error
j.s.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at c.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at c.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at c.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at c.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at c.m.c.j.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	... 110 frames truncated
Caused by: c.m.cj.exceptions.CJException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:105)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:151)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:124)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:153)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
	... 5 frames truncated
	... 114 common frames omitted
Caused by: c.m.c.e.UnableToConnectException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:85)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130)
	... 120 common frames omitted
2024-08-10 09:32:25.358|main|ERROR|o.s.boot.SpringApplication.reportFailure:821|IGNORE|||||||||||||||||||||||||||||Application run failed
o.s.b.f.BeanCreationException: Error creating bean with name 'demoController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoPublishServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoPublisher': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoRepositoryImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoMapper' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-infrastructure\target\classes\com\zyhl\yun\liteflow\persistence\mapper\DemoMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class]: Invocation of init method failed; nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at o.s.c.a.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at o.s.b.f.s.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at o.s.b.f.s.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at o.s.b.f.s.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at o.s.b.f.s.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at o.s.b.f.s.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at o.s.c.s.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	... 6 frames truncated
Caused by: o.s.b.f.BeanCreationException: Error creating bean with name 'demoPublishServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoPublisher': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoRepositoryImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoMapper' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-infrastructure\target\classes\com\zyhl\yun\liteflow\persistence\mapper\DemoMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/d...2024-08-10 09:36:05.369|main|ERROR|c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||init datasource error, url: jdbc:p6spy:mysql://127.0.0.1:3306/share?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
j.s.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at c.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at c.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at c.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at c.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at c.m.c.j.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	... 110 frames truncated
Caused by: c.m.cj.exceptions.CJException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:105)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:151)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:124)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:153)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
	... 5 frames truncated
	... 114 common frames omitted
Caused by: c.m.c.e.UnableToConnectException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:85)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130)
	... 120 common frames omitted
2024-08-10 09:36:05.373|main|ERROR|c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} init error
j.s.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at c.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at c.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at c.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at c.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at c.m.c.j.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	... 110 frames truncated
Caused by: c.m.cj.exceptions.CJException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:105)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:151)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:124)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:153)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
	... 5 frames truncated
	... 114 common frames omitted
Caused by: c.m.c.e.UnableToConnectException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:85)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130)
	... 120 common frames omitted
2024-08-10 09:36:05.401|main|ERROR|o.s.boot.SpringApplication.?:?|IGNORE|||||||||||||||||||||||||||||Application run failed
o.s.b.f.BeanCreationException: Error creating bean with name 'demoController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoPublishServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoPublisher': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoRepositoryImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoMapper' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-infrastructure\target\classes\com\zyhl\yun\liteflow\persistence\mapper\DemoMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class]: Invocation of init method failed; nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at o.s.c.a.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at o.s.b.f.s.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at o.s.b.f.s.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at o.s.b.f.s.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at o.s.b.f.s.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at o.s.b.f.s.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at o.s.c.s.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	... 6 frames truncated
Caused by: o.s.b.f.BeanCreationException: Error creating bean with name 'demoPublishServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoPublisher': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoRepositoryImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoMapper' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-infrastructure\target\classes\com\zyhl\yun\liteflow\persistence\mapper\DemoMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/d...2024-08-10 09:39:38.881|main|ERROR|c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||init datasource error, url: jdbc:p6spy:mysql://127.0.0.1:3306/share?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
j.s.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at c.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at c.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at c.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at c.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at c.m.c.j.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	... 110 frames truncated
Caused by: c.m.cj.exceptions.CJException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:105)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:151)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:124)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:153)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
	... 5 frames truncated
	... 114 common frames omitted
Caused by: c.m.c.e.UnableToConnectException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:85)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130)
	... 120 common frames omitted
2024-08-10 09:39:38.885|main|ERROR|c.a.druid.pool.DruidDataSource.?:?|IGNORE|||||||||||||||||||||||||||||{dataSource-1} init error
j.s.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at c.m.c.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at c.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:898)
	at c.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	at c.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
	at c.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
	at c.m.c.j.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	... 110 frames truncated
Caused by: c.m.cj.exceptions.CJException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:105)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:151)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:124)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:153)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
	... 5 frames truncated
	... 114 common frames omitted
Caused by: c.m.c.e.UnableToConnectException: Public Key Retrieval is not allowed
	at s.r.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
	at s.r.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at s.r.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:61)
	at c.m.c.e.ExceptionFactory.createException(ExceptionFactory.java:85)
	at c.m.c.p.a.a.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130)
	... 120 common frames omitted
2024-08-10 09:39:38.913|main|ERROR|o.s.boot.SpringApplication.?:?|IGNORE|||||||||||||||||||||||||||||Application run failed
o.s.b.f.BeanCreationException: Error creating bean with name 'demoController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoPublishServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoPublisher': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoRepositoryImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoMapper' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-infrastructure\target\classes\com\zyhl\yun\liteflow\persistence\mapper\DemoMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class]: Invocation of init method failed; nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at o.s.c.a.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at o.s.b.f.s.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at o.s.b.f.s.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at o.s.b.f.s.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at o.s.b.f.s.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at o.s.b.f.s.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at o.s.c.s.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920)
	... 6 frames truncated
Caused by: o.s.b.f.BeanCreationException: Error creating bean with name 'demoPublishServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'infoPublisher': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoRepositoryImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoMapper' defined in file [C:\Users\25538\source\java\share-liteflow\share-liteflow-infrastructure\target\classes\com\zyhl\yun\liteflow\persistence\mapper\DemoMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/d...2024-08-10 09:48:23.081|main|ERROR|o.s.boot.SpringApplication.reportFailure:821|IGNORE|||||||||||||||||||||||||||||Application run failed
o.s.b.f.BeanCreationException: Error creating bean with name 'redisson' defined in class path resource [com/zyhl/hcy/plugin/redis/support/RedisAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is org.redisson.client.RedisConnectionException: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at o.s.b.f.s.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at o.s.b.f.s.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at o.s.b.f.s.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at o.s.b.f.s.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at o.s.b.f.s.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at o.s.b.f.s.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	... 8 frames truncated
Caused by: o.s.b.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is org.redisson.client.RedisConnectionException: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at o.s.b.f.s.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at o.s.b.f.s.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 17 common frames omitted
Caused by: o.r.c.RedisConnectionException: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at o.r.c.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:221)
	at o.r.c.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:191)
	at o.r.config.ConfigSupport.createConnectionManager(ConfigSupport.java:220)
	at org.redisson.Redisson.<init>(Redisson.java:69)
	at org.redisson.Redisson.create(Redisson.java:114)
	at c.z.h.p.r.s.RedisAutoConfiguration.redisson(RedisAutoConfiguration.java:88)
	at c.z.h.p.r.s.RedisAutoConfiguration$$EnhancerBySpringCGLIB$$fcd3d525.CGLIB$redisson$1(<generated>)
	at c.z.h.p.r.s.RedisAutoConfiguration$$EnhancerBySpringCGLIB$$fcd3d525$$FastClassBySpringCGLIB$$9a85c2ce.invoke(<generated>)
	at o.s.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at o.s.c.a.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	... 6 frames truncated
	... 18 common frames omitted
Caused by: j.u.c.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at j.u.c.CompletableFuture.reportGet(CompletableFuture.java:357)
	at j.u.c.CompletableFuture.get(CompletableFuture.java:1928)
	at o.r.c.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:217)
	... 33 common frames omitted
Caused by: o.r.c.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at o.r.c.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:129)
	at j.u.c.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at j.u.c.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at j.u.c.CompletableFuture.postComplete(CompletableFuture.java:488)
	at j.u.c.CompletableFuture.completeExceptionally(Comp...2024-08-10 09:49:51.238|main|ERROR|o.s.boot.SpringApplication.?:?|IGNORE|||||||||||||||||||||||||||||Application run failed
o.s.b.f.BeanCreationException: Error creating bean with name 'redisson' defined in class path resource [com/zyhl/hcy/plugin/redis/support/RedisAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is org.redisson.client.RedisConnectionException: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at o.s.b.f.s.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at o.s.b.f.s.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at o.s.b.f.s.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at o.s.b.f.s.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at o.s.b.f.s.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at o.s.b.f.s.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	... 8 frames truncated
Caused by: o.s.b.BeanInstantiationException: Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception; nested exception is org.redisson.client.RedisConnectionException: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at o.s.b.f.s.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at o.s.b.f.s.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 17 common frames omitted
Caused by: o.r.c.RedisConnectionException: java.util.concurrent.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at o.r.c.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:221)
	at o.r.c.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:191)
	at o.r.config.ConfigSupport.createConnectionManager(ConfigSupport.java:220)
	at org.redisson.Redisson.<init>(Redisson.java:69)
	at org.redisson.Redisson.create(Redisson.java:114)
	at c.z.h.p.r.s.RedisAutoConfiguration.redisson(RedisAutoConfiguration.java:88)
	at c.z.h.p.r.s.RedisAutoConfiguration$$EnhancerBySpringCGLIB$$a5404c6b.CGLIB$redisson$1(<generated>)
	at c.z.h.p.r.s.RedisAutoConfiguration$$EnhancerBySpringCGLIB$$a5404c6b$$FastClassBySpringCGLIB$$bf9933f9.invoke(<generated>)
	at o.s.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at o.s.c.a.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	... 6 frames truncated
	... 18 common frames omitted
Caused by: j.u.c.ExecutionException: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at j.u.c.CompletableFuture.reportGet(CompletableFuture.java:357)
	at j.u.c.CompletableFuture.get(CompletableFuture.java:1928)
	at o.r.c.MasterSlaveConnectionManager.doConnect(MasterSlaveConnectionManager.java:217)
	... 33 common frames omitted
Caused by: o.r.c.RedisConnectionException: Unable to connect to Redis server: localhost/127.0.0.1:6379
	at o.r.c.pool.ConnectionPool.lambda$createConnection$0(ConnectionPool.java:129)
	at j.u.c.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at j.u.c.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at j.u.c.CompletableFuture.postComplete(CompletableFuture.java:488)
	at j.u.c.CompletableFuture.completeExceptionally(Comp...2024-08-10 09:50:58.433|main-thread-0|ERROR|c.y.liteflow.core.FlowExecutor.error:375|IGNORE|||||||||||||||||||||||||||||[330908071f804a98b7788f9225adc812]:couldn't find chain with the id[chain1]
c.y.l.e.ChainNotFoundException: couldn't find chain with the id[chain1]
	at c.y.liteflow.core.FlowExecutor.doExecute(FlowExecutor.java:451)
	at c.y.liteflow.core.FlowExecutor.execute2Resp(FlowExecutor.java:369)
	at c.y.liteflow.core.FlowExecutor.execute2Resp(FlowExecutor.java:283)
	at c.y.liteflow.core.FlowExecutor.lambda$execute2Future$0(FlowExecutor.java:334)
	at com.alibaba.ttl.TtlCallable.call(TtlCallable.java:62)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2024-08-10 09:53:17.077|main-thread-0|ERROR|c.y.liteflow.flow.element.Node.error:346|IGNORE|||||||||||||||||||||||||||||[0d4204ede78e48bb9e5a8d6a4b06c28a]:component[userInfo] cause error,error:null
2024-08-10 09:53:17.080|main-thread-0|ERROR|c.y.liteflow.core.FlowExecutor.?:?|IGNORE|||||||||||||||||||||||||||||[0d4204ede78e48bb9e5a8d6a4b06c28a]:chain[chain1] execute error on slot[0]
java.lang.NullPointerException: null
	at c.z.y.l.a.context.UserContext.setAccount(UserContext.java:18)
	at c.z.y.l.a.cmp.UserInfoNode.process(UserInfoNode.java:48)
	at c.y.l.core.NodeComponent.execute(NodeComponent.java:108)
	at c.y.l.f.executor.NodeExecutor.execute(NodeExecutor.java:32)
	at c.y.l.f.e.DefaultNodeExecutor.execute(DefaultNodeExecutor.java:15)
	at c.y.liteflow.flow.element.Node.execute(Node.java:154)
	at c.y.l.f.e.c.ThenCondition.executeCondition(ThenCondition.java:44)
	at c.y.l.flow.element.Condition.execute(Condition.java:57)
	at c.y.l.flow.element.Chain.execute(Chain.java:106)
	at c.y.liteflow.core.FlowExecutor.doExecute(FlowExecutor.java:455)
	... 8 frames truncated
2024-08-10 09:54:52.974|main-thread-0|ERROR|c.y.liteflow.core.FlowExecutor.error:375|IGNORE|||||||||||||||||||||||||||||[3a0c5e6a5c16474396e9dcdc8e62259d]:couldn't find chain with the id[chain1]
c.y.l.e.ChainNotFoundException: couldn't find chain with the id[chain1]
	at c.y.liteflow.core.FlowExecutor.doExecute(FlowExecutor.java:451)
	at c.y.liteflow.core.FlowExecutor.execute2Resp(FlowExecutor.java:369)
	at c.y.liteflow.core.FlowExecutor.execute2Resp(FlowExecutor.java:283)
	at c.y.liteflow.core.FlowExecutor.lambda$execute2Future$0(FlowExecutor.java:334)
	at com.alibaba.ttl.TtlCallable.call(TtlCallable.java:62)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2024-08-10 09:55:25.943|main-thread-0|ERROR|c.y.liteflow.core.FlowExecutor.error:375|IGNORE|||||||||||||||||||||||||||||[d84f10b74f54454b8fdde50b9e0bfd5e]:couldn't find chain with the id[chain1]
c.y.l.e.ChainNotFoundException: couldn't find chain with the id[chain1]
	at c.y.liteflow.core.FlowExecutor.doExecute(FlowExecutor.java:451)
	at c.y.liteflow.core.FlowExecutor.execute2Resp(FlowExecutor.java:369)
	at c.y.liteflow.core.FlowExecutor.execute2Resp(FlowExecutor.java:283)
	at c.y.liteflow.core.FlowExecutor.lambda$execute2Future$0(FlowExecutor.java:334)
	at com.alibaba.ttl.TtlCallable.call(TtlCallable.java:62)
	at j.util.concurrent.FutureTask.run(FutureTask.java:266)
	at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2024-08-10 09:57:30.575|main-thread-0|ERROR|c.y.liteflow.flow.element.Node.error:346|IGNORE|||||||||||||||||||||||||||||[709e7188ca40467f8a7768b5d1126fda]:component[userInfo] cause error,error:null
2024-08-10 09:57:30.576|main-thread-0|ERROR|c.y.liteflow.core.FlowExecutor.?:?|IGNORE|||||||||||||||||||||||||||||[709e7188ca40467f8a7768b5d1126fda]:chain[chain1] execute error on slot[0]
java.lang.NullPointerException: null
	at c.z.y.l.a.context.UserContext.setAccount(UserContext.java:18)
	at c.z.y.l.a.cmp.UserInfoNode.process(UserInfoNode.java:48)
	at c.y.l.core.NodeComponent.execute(NodeComponent.java:108)
	at c.y.l.f.executor.NodeExecutor.execute(NodeExecutor.java:32)
	at c.y.l.f.e.DefaultNodeExecutor.execute(DefaultNodeExecutor.java:15)
	at c.y.liteflow.flow.element.Node.execute(Node.java:154)
	at c.y.l.f.e.c.ThenCondition.executeCondition(ThenCondition.java:44)
	at c.y.l.flow.element.Condition.execute(Condition.java:57)
	at c.y.l.flow.element.Chain.execute(Chain.java:106)
	at c.y.liteflow.core.FlowExecutor.doExecute(FlowExecutor.java:455)
	... 8 frames truncated
2024-08-10 09:58:50.880|main-thread-0|ERROR|c.z.y.l.a.cmp.UserInfoNode.?:?|IGNORE|||||||||||||||||||||||||||||输入0或1
j.util.InputMismatchException: null
	at java.util.Scanner.throwFor(Scanner.java:864)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextInt(Scanner.java:2117)
	at java.util.Scanner.nextInt(Scanner.java:2076)
	at c.z.y.l.a.cmp.UserInfoNode.process(UserInfoNode.java:35)
	at c.y.l.core.NodeComponent.execute(NodeComponent.java:108)
	at c.y.l.f.executor.NodeExecutor.execute(NodeExecutor.java:32)
	at c.y.l.f.e.DefaultNodeExecutor.execute(DefaultNodeExecutor.java:15)
	at c.y.liteflow.flow.element.Node.execute(Node.java:154)
	at c.y.l.f.e.c.ThenCondition.executeCondition(ThenCondition.java:44)
	... 11 frames truncated
2024-08-10 10:00:50.562|main-thread-0|ERROR|c.y.liteflow.flow.element.Node.error:346|IGNORE|||||||||||||||||||||||||||||[70de049016c74089917de0f31e064eab]:component[userInfo] cause error,error:null
2024-08-10 10:00:50.562|main-thread-0|ERROR|c.y.liteflow.core.FlowExecutor.?:?|IGNORE|||||||||||||||||||||||||||||[70de049016c74089917de0f31e064eab]:chain[chain1] execute error on slot[0]
java.lang.NullPointerException: null
	at c.z.y.l.a.context.UserContext.setAccount(UserContext.java:18)
	at c.z.y.l.a.cmp.UserInfoNode.process(UserInfoNode.java:49)
	at c.y.l.core.NodeComponent.execute(NodeComponent.java:108)
	at c.y.l.f.executor.NodeExecutor.execute(NodeExecutor.java:32)
	at c.y.l.f.e.DefaultNodeExecutor.execute(DefaultNodeExecutor.java:15)
	at c.y.liteflow.flow.element.Node.execute(Node.java:154)
	at c.y.l.f.e.c.ThenCondition.executeCondition(ThenCondition.java:44)
	at c.y.l.flow.element.Condition.execute(Condition.java:57)
	at c.y.l.flow.element.Chain.execute(Chain.java:106)
	at c.y.liteflow.core.FlowExecutor.doExecute(FlowExecutor.java:455)
	... 8 frames truncated
2024-08-10 10:02:45.705|main-thread-0|ERROR|c.y.liteflow.flow.element.Node.error:346|IGNORE|||||||||||||||||||||||||||||[cf6c07af8c5f48268773a12d3a241463]:component[userInfo] cause error,error:null
2024-08-10 10:02:45.707|main-thread-0|ERROR|c.y.liteflow.core.FlowExecutor.error:375|IGNORE|||||||||||||||||||||||||||||[cf6c07af8c5f48268773a12d3a241463]:chain[chain1] execute error on slot[0]
java.lang.NullPointerException: null
	at c.z.y.l.a.cmp.UserInfoNode.process(UserInfoNode.java:30)
	at c.y.l.core.NodeComponent.execute(NodeComponent.java:108)
	at c.y.l.f.executor.NodeExecutor.execute(NodeExecutor.java:32)
	at c.y.l.f.e.DefaultNodeExecutor.execute(DefaultNodeExecutor.java:15)
	at c.y.liteflow.flow.element.Node.execute(Node.java:154)
	at c.y.l.f.e.c.ThenCondition.executeCondition(ThenCondition.java:44)
	at c.y.l.flow.element.Condition.execute(Condition.java:57)
	at c.y.l.flow.element.Chain.execute(Chain.java:106)
	at c.y.liteflow.core.FlowExecutor.doExecute(FlowExecutor.java:455)
	at c.y.liteflow.core.FlowExecutor.execute2Resp(FlowExecutor.java:369)
	... 7 frames truncated
2024-08-10 10:06:13.147|main-thread-0|ERROR|c.z.y.l.e.s.i.UserInfoServiceImpl.getUserDomainEntity:49|IGNORE|||||||||||||||||||||||||||||user-server executing POST http://user-server/user/getUser
2024-08-10 10:18:10.789|main-thread-0|ERROR|c.z.y.l.e.s.i.UserInfoServiceImpl.getUserDomainEntity:49|IGNORE|||||||||||||||||||||||||||||user-server executing POST http://user-server/user/getUser
2024-08-10 10:32:32.289|redisson-netty-2-17|ERROR|o.r.c.h.ErrorsLoggingHandler.?:?|IGNORE|||||||||||||||||||||||||||||Exception occured. Channel: [id: 0xa4f09a1e, L:/127.0.0.1:56996 - R:localhost/127.0.0.1:6379]
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(SocketDispatcher.java)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:378)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256)
	at i.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at i.n.c.s.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at i.n.c.n.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at i.n.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	... 7 frames truncated
2024-08-10 11:10:52.664|main-thread-0|ERROR|c.z.y.l.e.s.i.UserInfoServiceImpl.getUserDomainEntity:50|IGNORE|||||||||||||||||||||||||||||user-server executing POST http://user-server/user/getUser
2024-08-10 15:46:57.685|main|ERROR|c.a.nacos.common.remote.client.printIfErrorEnabled:99|IGNORE|||||||||||||||||||||||||||||Send request fail, request = InstanceRequest{headers={}, requestId='null'}, retryTimes = 0, errorMessage = errCode: 400, errMsg: Current service DEFAULT_GROUP@@file-server is persistent service, can't register ephemeral instance. 
2024-08-10 15:46:57.688|main|ERROR|c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||Send request fail, request = InstanceRequest{headers={}, requestId='null'}, retryTimes = 1, errorMessage = errCode: 400, errMsg: Current service DEFAULT_GROUP@@file-server is persistent service, can't register ephemeral instance. 
2024-08-10 15:46:57.691|main|ERROR|c.a.nacos.common.remote.client.?:?|IGNORE|||||||||||||||||||||||||||||Send request fail, request = InstanceRequest{headers={}, requestId='null'}, retryTimes = 2, errorMessage = errCode: 400, errMsg: Current service DEFAULT_GROUP@@file-server is persistent service, can't register ephemeral instance. 
2024-08-10 15:46:57.694|main|ERROR|c.a.c.n.r.NacosServiceRegistry.register:80|IGNORE|||||||||||||||||||||||||||||nacos registry, file-server register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='192.168.71.1:8848', username='', password='', endpoint='', namespace='', watchDelay=30000, logName='', service='file-server', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.71.1', networkInterface='', port=8083, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, instanceEnabled=true, ephemeral=true, failureToleranceEnabled=false}, ipDeleteTimeout=null, failFast=true}},
c.a.n.a.e.NacosException: Request nacos server failed: 
	at c.a.n.c.n.r.g.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:290)
	at c.a.n.c.n.r.g.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129)
	at c.a.n.c.n.r.g.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115)
	at c.a.n.c.n.r.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:94)
	at c.a.n.c.n.NacosNamingService.registerInstance(NacosNamingService.java:145)
	at c.a.c.n.r.NacosServiceRegistry.register(NacosServiceRegistry.java:74)
	at o.s.c.c.s.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:232)
	at c.a.c.n.r.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78)
	at o.s.c.c.s.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:133)
	at o.s.c.c.s.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:98)
	... 21 frames truncated
Caused by: c.a.n.a.e.NacosException: errCode: 400, errMsg: Current service DEFAULT_GROUP@@file-server is persistent service, can't register ephemeral instance. 
	at c.a.n.c.r.client.RpcClient.request(RpcClient.java:669)
	at c.a.n.c.r.client.RpcClient.request(RpcClient.java:630)
	at c.a.n.c.n.r.g.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:280)
	... 30 common frames omitted
2024-08-10 15:46:58.805|main|ERROR|o.s.boot.SpringApplication.reportFailure:821|IGNORE|||||||||||||||||||||||||||||Application run failed
o.s.c.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is java.lang.reflect.UndeclaredThrowableException
	at o.s.c.s.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
	at o.s.c.s.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
	at o.s.c.s.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at o.s.c.s.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at o.s.c.s.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at o.s.c.s.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:937)
	at o.s.c.s.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at o.s.b.w.s.c.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at o.s.boot.SpringApplication.refresh(SpringApplication.java:731)
	... 3 frames truncated
Caused by: j.l.r.UndeclaredThrowableException: null
	at o.s.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147)
	at c.a.c.n.r.NacosServiceRegistry.register(NacosServiceRegistry.java:82)
	at o.s.c.c.s.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:232)
	at c.a.c.n.r.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78)
	at o.s.c.c.s.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:133)
	at o.s.c.c.s.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:98)
	at o.s.c.c.s.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:86)
	at o.s.c.c.s.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47)
	at o.s.c.e.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at o.s.c.e.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	... 5 frames truncated
	... 12 common frames omitted
Caused by: c.a.n.a.e.NacosException: Request nacos server failed: 
	at c.a.n.c.n.r.g.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:290)
	at c.a.n.c.n.r.g.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129)
	at c.a.n.c.n.r.g.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115)
	at c.a.n.c.n.r.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:94)
	at c.a.n.c.n.NacosNamingService.registerInstance(NacosNamingService.java:145)
	at c.a.c.n.r.NacosServiceRegistry.register(NacosServiceRegistry.java:74)
	... 25 common frames omitted
Caused by: c.a.n.a.e.NacosException: errCode: 400, errMsg: Current service DEFAULT_GROUP@@file-server is persistent service, can't register ephemeral instance. 
	at c.a.n.c.r.client.RpcClient.request(RpcClient.java:669)
	at c.a.n.c.r.client.RpcClient.request(RpcClient.java:630)
	at c.a.n.c.n.r.g.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:280)
	... 30 common frames omitted
